# Generated by Django 5.2 on 2025-04-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_date'], 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name_plural': 'Medicines'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date'], 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name_plural': 'Patients'},
        ),
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_pics/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
